"""Original models

Revision ID: 44f88388a225
Revises: ac246effad31
Create Date: 2026-05-17 14:33:23.095832

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "44f88388a225"
down_revision: Union[str, Sequence[str], None] = "ac246effad31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
