"""Original models

Revision ID: ac246effad31
Revises: 
Create Date: 2026-05-17 14:06:46.966759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac246effad31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_time_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailychange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_change', sa.Float(), nullable=False),
    sa.Column('daily_change_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('type', sa.Enum('SHARES', 'CRYPTO', name='investmenttype'), nullable=False),
    sa.Column('live_price', sa.Float(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dividendpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['investment_key'], ['investment.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'investment_key')
    )
    op.create_table('dividendreinvestment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['investment_key'], ['investment.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'investment_key')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_key'], ['investment.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'investment_key')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sa.Enum('XASX', 'XAMS', 'XBOM', 'XBRU', 'XFRA', 'XHKG', 'XJPX', 'XKOS', 'XLIS', 'XLON', 'XMIL', 'XMSM', 'XNAS', 'XNSE', 'XNYS', 'XOSL', 'XSAU', 'XSHE', 'XSHG', 'XSWX', 'XTAI', 'XTSE', name='exchanges'), nullable=False),
    sa.Column('platform', sa.Enum('CMC', 'LINK', 'BOARDROOM', 'DIRECT', 'IPO', name='platforms'), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_key'], ['investment.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'trade_count', 'investment_key')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sa.Enum('XASX', 'XAMS', 'XBOM', 'XBRU', 'XFRA', 'XHKG', 'XJPX', 'XKOS', 'XLIS', 'XLON', 'XMIL', 'XMSM', 'XNAS', 'XNSE', 'XNYS', 'XOSL', 'XSAU', 'XSHE', 'XSHG', 'XSWX', 'XTAI', 'XTSE', name='exchanges'), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_key'], ['investment.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'trade_count', 'investment_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('purchase')
    op.drop_table('history')
    op.drop_table('dividendreinvestment')
    op.drop_table('dividendpayment')
    op.drop_table('investment')
    op.drop_table('dailychange')
    op.drop_table('configuration')
    # ### end Alembic commands ###
